In [ ]:
#importing libraries
import pandas as pd
import numpy as np

In [ ]:
#reading data from .csv file 
data=pd.read_csv('/content/Social_Network_Ads.csv')

In [ ]:
#checking the dataframe for feautres.
data

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [ ]:
#splitting the feautures and classification into two data frames
#'x' contains all the features
#'Y contains wheather customer is churned or not'
# 0- un churned & 1- churned.
x=data[['Age','EstimatedSalary']]
y=data['Purchased']

In [ ]:
# importing all the data into testing and train set using train_test_split in built function
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [ ]:
#importing function called Standardscaler to preprocses and transform the scaling the features.
from sklearn.preprocessing import StandardScaler
model1=StandardScaler()
x_train=model1.fit_transform(x_train)
x_test=model1.fit_transform(x_test)

In [ ]:
#importing gaussian naive bayes classifier for the prediction
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train, y_train)
y_pred=model.predict(x_test)

In [ ]:
#for accuracy metrics using confusion matrix and accuracy score.
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
cm


array([[51,  4],
       [ 4, 21]])

In [ ]:
accuracy_score(y_test,y_pred)

0.9

In [ ]:
from sklearn.metrics import matthews_corrcoef
mc=matthews_corrcoef(y_test,y_pred)

In [ ]:
mc

0.7672727272727272

In [ ]:
# predicting the churn usong RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators = 100) 
clf.fit(x_train, y_train)
y_pred = clf.predict(x_test)

In [ ]:
y_pred

array([1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
mc=matthews_corrcoef(y_test,y_pred)
mc

0.7734968906252137

In [ ]:
#classification using KNN algorithim
K = []
training = []
test = []
scores = {}
from sklearn.neighbors import KNeighborsClassifier

clf = KNeighborsClassifier(n_neighbors = 4)
clf.fit(x_train, y_train)
training_score = clf.score(x_train, y_train)
test_score = clf.score(x_test, y_test)
test_score


0.9125

In [ ]:
mc=matthews_corrcoef(y_test,y_pred)
mc

0.7734968906252137

In [ ]:
accuracy_score(y_test,y_pred)

0.9

In [ ]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[50,  5],
       [ 3, 22]])

In [ ]:
accuracy_score(y_test,y_pred)

0.9

In [ ]:
from sklearn import svm
model = svm.SVC(kernel = 'linear', random_state = 0, C=1.0)
model.fit(x_train,y_train)
ypred=model.predict(x_test)
cm=confusion_matrix(y_test,y_pred)
cm
#accuracy_score(y_test,y_pred)

array([[51,  4],
       [ 4, 21]])

In [ ]:
from sklearn.metrics import matthews_corrcoef
mc=matthews_corrcoef(y_test,y_pred)
mc